# Generated by Django 4.1.1 on 2022-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_degreerequirement_course_alter_section_day1_and_more'),
        ('account', '0002_user_degree_user_semester_take_finish_user_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='section',
        ),
        migrations.RemoveField(
            model_name='take',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='user',
            name='take',
        ),
        migrations.AddField(
            model_name='user',
            name='finished_courses',
            field=models.ManyToManyField(related_name='users_that_finished', to='app.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(related_name='students', to='app.section'),
        ),
        migrations.DeleteModel(
            name='Finish',
        ),
        migrations.DeleteModel(
            name='Take',
        ),
    ]
