# Generated by Django 4.1.1 on 2022-10-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_course_name_alter_degree_name'),
        ('account', '0003_remove_take_section_remove_take_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.degree'),
        ),
        migrations.AlterField(
            model_name='user',
            name='finished_courses',
            field=models.ManyToManyField(blank=True, related_name='users_that_finished', to='app.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='students', to='app.section'),
        ),
    ]
