# Generated by Django 4.1.1 on 2022-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sectiontime_alter_course_hours_alter_degree_hours_ca_and_more'),
        ('account', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_times',
            field=models.ManyToManyField(blank=True, related_name='users_free', to='app.sectiontime'),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_courses',
            field=models.ManyToManyField(blank=True, related_name='users_interested', to='app.course'),
        ),
    ]
