# Generated by Django 4.1.1 on 2022-12-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_end',
            field=models.IntegerField(default=0, verbose_name='Expected Hours'),
        ),
    ]
