branch-defaults:
  main:
    environment: Auxgrade-env
  rodrigo:
    environment: Auxgrade-env
environment-defaults:
  Auxgrade-env:
    branch: null
    repository: null
global:
  application_name: AuxGrade
  default_ec2_keyname: auxgrade-eb-1
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
