# Generated by Django 4.1.1 on 2022-10-03 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='Nome da Disciplina')),
                ('semester', models.SmallIntegerField(verbose_name='Semestre')),
                ('credits', models.SmallIntegerField(verbose_name='Creditos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='Nome do Curso')),
                ('credits_total', models.SmallIntegerField(verbose_name='Creditos Totais')),
                ('credits_core', models.SmallIntegerField(verbose_name='Creditos Fixas')),
                ('credits_elective', models.SmallIntegerField(verbose_name='Creditos Eletivas')),
                ('credits_ca', models.SmallIntegerField(verbose_name='Creditos Atividades Complementares')),
                ('credits_thesis', models.SmallIntegerField(verbose_name='Creditos TCC')),
                ('credits_internship', models.SmallIntegerField(verbose_name='Creditos Estagio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
