# Generated by Django 4.1.1 on 2022-10-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='core_courses',
            field=models.ManyToManyField(db_table='Disciplinas Fixas', related_name='degree_core_set', to='app.course'),
        ),
        migrations.AddField(
            model_name='degree',
            name='elective_courses',
            field=models.ManyToManyField(db_table='Disciplinas Eletivas', related_name='degree_elective_set', to='app.course'),
        ),
        migrations.AddField(
            model_name='degree',
            name='required_courses',
            field=models.ManyToManyField(db_table='Disciplinas Requeridas', related_name='degree_required_set', to='app.course'),
        ),
    ]
