# Generated by Django 4.1.1 on 2022-10-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_degree_core_courses_degree_elective_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='credits_ca',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='credits_core',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='credits_elective',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='credits_internship',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='credits_thesis',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='credits_total',
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='hours_ca',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Atividades Complementares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='hours_core',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Fixas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='hours_elective',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Eletivas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='hours_internship',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Estagio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='hours_thesis',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria TCC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='hours_total',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Total'),
            preserve_default=False,
        ),
    ]
