# Generated by Django 4.1.1 on 2022-10-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_course_credits_remove_degree_credits_ca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='required_courses',
        ),
        migrations.AlterField(
            model_name='degree',
            name='core_courses',
            field=models.ManyToManyField(related_name='degree_core_set', to='app.course'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='elective_courses',
            field=models.ManyToManyField(related_name='degree_elective_set', to='app.course'),
        ),
    ]
