# Generated by Django 4.1.1 on 2022-10-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_requirement_degree_required_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='DegreeRequirement',
        ),
    ]
