# Generated by Django 4.1.1 on 2022-10-03 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_degree_required_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='time2',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Horario 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='time3',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Horario 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='time1',
            field=models.TimeField(verbose_name='Horario 1'),
        ),
    ]
