# Generated by Django 4.1.1 on 2022-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_section_time2_section_time3_alter_section_time1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time2',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario 2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='time3',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario 3'),
        ),
    ]
