# Generated by Django 4.1.1 on 2022-10-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_degreerequirement_course_alter_section_day1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreerequirement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='degreerequirement',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='degree_requirement',
        ),
        migrations.AddField(
            model_name='course',
            name='required_courses',
            field=models.ManyToManyField(blank=True, related_name='courses_that_require', to='app.course'),
        ),
        migrations.AddField(
            model_name='degree',
            name='required_courses',
            field=models.ManyToManyField(blank=True, related_name='required_in_degrees', to='app.course'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='core_courses',
            field=models.ManyToManyField(related_name='core_in_degrees', to='app.course'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='elective_courses',
            field=models.ManyToManyField(related_name='elective_in_degrees', to='app.course'),
        ),
        migrations.DeleteModel(
            name='CourseRequirement',
        ),
        migrations.DeleteModel(
            name='DegreeRequirement',
        ),
    ]
