# Generated by Django 4.1.1 on 2022-10-19 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_is_interdisciplinary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='core_courses',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='elective_courses',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='required_courses',
        ),
        migrations.CreateModel(
            name='DegreeCourse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('course_type', models.CharField(choices=[('CO', 'Fixa'), ('EL', 'Eletiva'), ('IN', 'Interdisciplinar'), ('OP', 'Optativa')], max_length=2, verbose_name='Tipo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.degree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='degrees', through='app.DegreeCourse', to='app.course'),
        ),
    ]
