# Generated by Django 4.1.1 on 2022-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_course_is_interdisciplinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveSmallIntegerField(default=72, verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_ca',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Atividades Complementares'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_core',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Fixas'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_elective',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Eletivas'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_internship',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Estagio'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_thesis',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria TCC'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_total',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horaria Total'),
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='course_type',
            field=models.CharField(choices=[('CO', 'Fixa'), ('EL', 'Eletiva'), ('IN', 'Interdisciplinar'), ('OP', 'Optativa')], default='CO', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='section',
            name='day1',
            field=models.CharField(choices=[('MON', 'Segunda'), ('TUE', 'Terca'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sabado'), ('SUN', 'Domingo')], default='MON', max_length=3, verbose_name='Dia 1'),
        ),
        migrations.AlterField(
            model_name='section',
            name='time1',
            field=models.TimeField(default='08:00', verbose_name='Horario 1'),
        ),
    ]
