# Generated by Django 4.1.1 on 2022-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_course_hours_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='degreecourse',
            constraint=models.UniqueConstraint(fields=('degree', 'course'), name='unique_degreecourse_relation'),
        ),
    ]
