# Generated by Django 4.1.1 on 2022-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_course_name_alter_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome da Disciplina'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome da Turma'),
        ),
    ]
