# Generated by Django 4.1.1 on 2022-10-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_course_name_alter_degree_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='initials',
            field=models.CharField(max_length=3, null=True, verbose_name='Sigla'),
        ),
    ]
