# Generated by Django 4.1.1 on 2022-10-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='degreecourse',
            options={'ordering': ['degree__name', 'course__name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
    ]
