# Generated by Django 4.1.1 on 2022-11-22 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_course_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTime',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('day', models.CharField(choices=[('MON', 'Segunda'), ('TUE', 'Terça'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], default='MON', max_length=3, verbose_name='Dia')),
                ('time', models.TimeField(default='08:00', verbose_name='Horário')),
            ],
            options={
                'ordering': ['day', 'time'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveSmallIntegerField(default=72, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_ca',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horária Atividades Complementares'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_core',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horária Fixas'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_elective',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horária Eletivas'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_internship',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horária Estagio'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_thesis',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horária TCC'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='hours_total',
            field=models.SmallIntegerField(default=0, verbose_name='Carga Horária Total'),
        ),
        migrations.AlterField(
            model_name='section',
            name='day1',
            field=models.CharField(choices=[('MON', 'Segunda'), ('TUE', 'Terça'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], default='MON', max_length=3, verbose_name='Dia 1'),
        ),
        migrations.AlterField(
            model_name='section',
            name='day2',
            field=models.CharField(blank=True, choices=[('MON', 'Segunda'), ('TUE', 'Terça'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=3, verbose_name='Dia 2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='day3',
            field=models.CharField(blank=True, choices=[('MON', 'Segunda'), ('TUE', 'Terça'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=3, verbose_name='Dia 3'),
        ),
        migrations.AlterField(
            model_name='section',
            name='time1',
            field=models.TimeField(default='08:00', verbose_name='Horário 1'),
        ),
        migrations.AlterField(
            model_name='section',
            name='time2',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário 2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='time3',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário 3'),
        ),
        migrations.AddConstraint(
            model_name='sectiontime',
            constraint=models.UniqueConstraint(fields=('day', 'time'), name='unique_daytime_relation'),
        ),
    ]
