# Generated by Django 4.1.1 on 2022-11-24 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_remove_course_weight_courseweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='section',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='section',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time3',
        ),
        migrations.AddField(
            model_name='section',
            name='schedule',
            field=models.ManyToManyField(related_name='sections_scheduled', to='app.sectiontime'),
        ),
        migrations.AlterField(
            model_name='courseweight',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_weights', to='app.course'),
        ),
        migrations.AlterField(
            model_name='courseweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_weights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectiontime',
            name='day',
            field=models.CharField(choices=[('0', 'Segunda'), ('1', 'Terça'), ('2', 'Quarta'), ('3', 'Quinta'), ('4', 'Sexta'), ('5', 'Sábado'), ('6', 'Domingo')], default='0', max_length=1, verbose_name='Dia'),
        ),
        migrations.CreateModel(
            name='ComplimentaryHour',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('hours', models.PositiveSmallIntegerField(default=0, verbose_name='Horas')),
                ('group', models.CharField(choices=[('0', 'Atividade de Formação Cidadã'), ('1', 'Atividade de Extensão'), ('2', 'Atividade de Orientação Acadêmica'), ('3', 'Atividades Acadêmica, Profissional e Artística')], default='0', max_length=1, verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
