# Generated by Django 4.1.1 on 2022-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_section_day1_remove_section_day2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreecourse',
            name='course_type',
            field=models.CharField(choices=[('CO', 'Fixa'), ('EL', 'Eletiva'), ('IN', 'Interdisciplinar'), ('OP', 'Optativa'), ('G1', 'Eletiva Grupo 1'), ('G2', 'Eletiva Grupo 2'), ('G3', 'Eletiva Grupo 3')], default='CO', max_length=2, verbose_name='Tipo'),
        ),
    ]
